# Generated by Django 3.0.5 on 2021-02-22 01:49

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=512)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('location', djongo.models.fields.JSONField(blank=True, null=True)),
                ('plant', djongo.models.fields.JSONField(blank=True, null=True)),
                ('zones', djongo.models.fields.JSONField(blank=True, null=True)),
                ('aisles', djongo.models.fields.JSONField(blank=True, null=True)),
                ('bins', djongo.models.fields.JSONField(blank=True, null=True)),
                ('part_number', djongo.models.fields.JSONField(blank=True, null=True)),
                ('serial_number', djongo.models.fields.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.TextField()),
                ('repeat_every', models.TextField(blank=True, null=True)),
                ('on_day', djongo.models.fields.JSONField(blank=True, null=True)),
                ('for_month', djongo.models.fields.JSONField(blank=True, null=True)),
                ('time_zone_utc', models.TextField()),
                ('calendar_date', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
    ]
