# Generated by Django 3.0.5 on 2021-01-07 06:03

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('location', djongo.models.fields.JSONField(blank=True, null=True)),
                ('plant', djongo.models.fields.JSONField(blank=True, null=True)),
                ('zones', djongo.models.fields.JSONField(blank=True, null=True)),
                ('aisles', djongo.models.fields.JSONField(blank=True, null=True)),
                ('bins', djongo.models.fields.JSONField(blank=True, null=True)),
                ('part_number', djongo.models.fields.JSONField(blank=True, null=True)),
                ('serial_number', djongo.models.fields.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
