# Generated by Django 3.0.5 on 2021-01-21 06:07

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=512)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('location', djongo.models.fields.JSONField(blank=True, null=True)),
                ('plant', djongo.models.fields.JSONField(blank=True, null=True)),
                ('zones', djongo.models.fields.JSONField(blank=True, null=True)),
                ('aisles', djongo.models.fields.JSONField(blank=True, null=True)),
                ('bins', djongo.models.fields.JSONField(blank=True, null=True)),
                ('part_number', djongo.models.fields.JSONField(blank=True, null=True)),
                ('serial_number', djongo.models.fields.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('calendar_date', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
    ]
