version: '3'
services:
        client:
                build: ./client
                network_mode: "host"
        server:
                build: ./server
                network_mode: "host"
        mongo:
                image: mongo
                network_mode: "host"
                volumes:
                  - ./db:/data/db

