# Generated by Django 3.0.5 on 2021-01-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_items', models.ManyToManyField(to='inventory_item.Item')),
            ],
        ),
    ]
