# Generated by Django 3.0.5 on 2021-02-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('inventory_item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('initiated_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Active', 'Active')], default='Pending', max_length=12)),
                ('assigned_sk', models.ManyToManyField(blank=True, default=0, to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_by', to=settings.AUTH_USER_MODEL)),
                ('inventory_items', models.ManyToManyField(blank=True, default=0, to='inventory_item.Item')),
                ('organization', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('template_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit_template.AuditTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='BinToSK',
            fields=[
                ('bin_id', models.AutoField(primary_key=True, serialize=False)),
                ('Bin', models.CharField(max_length=256)),
                ('item_ids', djongo.models.fields.JSONField(blank=True, null=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], default='Pending', max_length=12)),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('init_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Audit')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('Batch_Number', models.CharField(default='N/A', max_length=256)),
                ('Location', models.CharField(default='N/A', max_length=256)),
                ('Plant', models.CharField(default='N/A', max_length=256)),
                ('Zone', models.CharField(default='N/A', max_length=256)),
                ('Aisle', models.IntegerField(null=True)),
                ('Bin', models.CharField(default='N/A', max_length=256)),
                ('Part_Number', models.CharField(default='N/A', max_length=256)),
                ('Part_Description', models.CharField(default='N/A', max_length=256)),
                ('Serial_Number', models.CharField(default='N/A', max_length=256)),
                ('Condition', models.CharField(default='N/A', max_length=256)),
                ('Category', models.CharField(default='N/A', max_length=256)),
                ('Owner', models.CharField(default='N/A', max_length=256)),
                ('Criticality', models.CharField(default='N/A', max_length=256)),
                ('Average_Cost', models.CharField(default='N/A', max_length=256)),
                ('Quantity', models.IntegerField(null=True)),
                ('Unit_of_Measure', models.CharField(default='N/A', max_length=256)),
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=256)),
                ('comment', models.TextField(blank=True)),
                ('flagged', models.BooleanField(default=False)),
                ('first_verified_on', models.DateTimeField(auto_now_add=True)),
                ('last_verified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Provided', 'Provided'), ('Missing', 'Missing'), ('New', 'New')], default='Pending', max_length=8)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Audit')),
                ('bin_to_sk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.BinToSK')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
