# Generated by Django 3.0.5 on 2021-01-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('audit_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='template_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit_template.AuditTemplate'),
        ),
    ]
