# Generated by Django 3.0.5 on 2021-02-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='accuracy',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
