# Generated by Django 3.0.5 on 2021-04-07 01:21

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=256, unique=True)),
                ('address', djongo.models.fields.JSONField()),
                ('status', models.BooleanField(default=False)),
                ('inventory_items_refresh_job', models.IntegerField(default=1)),
                ('repeat_interval', models.CharField(default='days', max_length=256)),
                ('ftp_location', models.CharField(max_length=256, null=True)),
                ('calendar_date', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
