# Generated by Django 3.0.5 on 2021-04-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='ftp_location',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='repeat_interval',
            field=models.CharField(default='days', max_length=256),
        ),
    ]
