# Generated by Django 3.0.5 on 2021-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='calendar_date',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
