# Generated by Django 3.0.5 on 2020-09-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('SA', 'System Admin'), ('IM', 'Inventory Manager'), ('SK', 'Stock Keeper')], max_length=2)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
