#!/bin/bash  
# script to setup, run and teardown end-to-end testing environment

DJANGO_PORT=8000

teardown () {
    trap SIGINT
    fuser -k $DJANGO_PORT/tcp 
    cd ../server
    yes yes | python manage.py flush --settings django_server.test_settings && echo "yes"           
    exit                     
}

trap teardown INT
cd server
source ./venv/bin/activate
yes yes | python manage.py flush --settings django_server.test_settings && echo "yes"
python manage.py makemigrations --settings django_server.test_settings
python manage.py migrate --settings django_server.test_settings 
python manage.py loaddata users.json --settings django_server.test_settings
fuser -k $DJANGO_PORT/tcp
python manage.py runserver 127.0.0.1:$DJANGO_PORT --settings django_server.test_settings &
cd ../client
ng e2e
teardown

trap SIGINT
