name: NgLint

on: 
  pull_request:
    branches:
      - master

jobs:
  nglint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: 'master'

    - name: Run Lint Master
      working-directory: client
      run: |
        npm i
        npm i -g @angular/cli
        REPORT=$(ng lint --force=true)
        echo "$REPORT"
        echo "MASTER_REPORT=${REPORT//$'\n'/'%0A'}" >> $GITHUB_ENV
    
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        ref: ${{github.ref}}

    - name: Npm install and Lint
      working-directory: client
      run: |         
        npm i
        npm i -g @angular/cli
        REPORT=$(ng lint --force=true)
        echo "$REPORT"
        echo "BRANCH_REPORT=${REPORT//$'\n'/'%0A'}" >> $GITHUB_ENV

    - name: Get Diff
      run: |
        DIFF_REPORT=$(python3 ./.github/diff.py "${MASTER_REPORT//$'%0A'/'\n'}" "${BRANCH_REPORT//$'%0A'/'\n'}")
        echo $DIFF_REPORT
        echo "DIFF=${DIFF_REPORT//$'\n'/'%0A'}" >> $GITHUB_ENV

    - name: Comment
      uses: actions/github-script@v3
      env:
          URL: ${{ github.event.pull_request.comments_url }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "NG Lint Report \n\n" + process.env.DIFF.replace("%0A","<br />")
          })
