name: build_server

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Makemigrations and Migrate
      working-directory: server
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Running tests with coverage using Pytest
      working-directory: server
      run: |
        pytest --cov --cov-report term
        pytest --cov --cov-report xml:cov.xml
    - name: Uploading tests coverage result to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true #(default = false)